blank_issues_enabled: false
contact_links:
  - name: J-Ono Search Tool Issues
    url: https://github.com/ObakeConstructs/j-ono-search/issues
    about: Issues with the J-Ono search tool should be reported here.
