name: Translation Problem
description: Report a translation problem
title: "[Translation Correction]: "
labels: ["translation problem"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to point out a translation issue.
  - type: input
    id: onomatopoeia
    attributes:
      label: Onomatopoeia
      description: Which japanese onomatopoeia is associated with this translation problem?
    validations:
      required: true
  - type: checkboxes
    id: field
    attributes:
      label: Problem Fields
      description: Which specific field(s) need attention?
      options:
        - label: japanese
        - label: literal
        - label: english equivalent
        - label: meaning
        - label: example image(s)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe this translation problem.
    validations:
      required: true
