name: New Example image 
description: Suggest a new example image
title: "[New Example]: "
labels: ["new image"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new example image.  Be sure to include the Japanese onomatopoeia in the title of the issue (either katakana or hiragana).
  - type: input
    id: literal
    attributes:
      label: English Literals
      description: What are some English words that have the same or similar meanings as the Japanese onomatopoeia?
    validations:
      required: true
  - type: input
    id: meaning
    attributes:
      label: English Meaning
      description: What is the general meaning or context of the onomatopoeia?
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Image Reference
      description: If you click this area, you can just drag and drop your new example image here (or click the paperclip icon below to attach an image file).
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: Source
      description: Where is your example image coming from (as in, what is the name of the manga series)?
    validations:
      required: true
  - type: input
    id: contribution
    attributes:
      label: Contributor Name
      description: What name would you like to show as the contributor for this example image? (Leave blank if you do not want contribution credit.)
    validations:
      required: false
      
